PatientHelpCare/Controllers/Chamber/ChambersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientHelpCare.DataModel;

namespace PatientHelpCare.Controllers
{
    public class ChambersController : Controller
    {
        private Doctor_InformationEntities _repository = new Doctor_InformationEntities();

        // GET: Chambers
        public async Task<ActionResult> Index()
        {
            string Id = _repository.AspNetUsers.Where(x => x.Email == HttpContext.User.Identity.Name).FirstOrDefault().Id;
            var chambers = _repository.Chambers.Include(c => c.Doctor);
            return View(await chambers.Where(x => x.DoctorId == Id).ToListAsync());
        }

        // GET: Chambers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamber chamber = await _repository.Chambers.FindAsync(id);
            if (chamber == null)
            {
                return HttpNotFound();
            }
            return View(chamber);
        }

        // GET: Chambers/Create
        public ActionResult Create()
        {
            ViewBag.DoctorId = new SelectList(_repository.Doctors, "DoctorId", "Firstname");
            return View();
        }

        // POST: Chambers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ChamberId,Name,FromDay,ToDay,StartTime,EndTime,Phone,Email,City,Area,Address1,Address2,ZipCode,DoctorId")] Chamber chamber)
        {
            if (ModelState.IsValid)
            {
                var user = this._repository.AspNetUsers.FirstOrDefault(x => x.Email == this.HttpContext.User.Identity.Name);
                chamber.DoctorId = user.Id;
                _repository.Chambers.Add(chamber);
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.DoctorId = new SelectList(_repository.Doctors, "DoctorId", "Firstname", chamber.DoctorId);
            return View(chamber);
        }

        // GET: Chambers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamber chamber = await _repository.Chambers.FindAsync(id);
            if (chamber == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorId = new SelectList(_repository.Doctors, "DoctorId", "Firstname", chamber.DoctorId);
            return View(chamber);
        }

        // POST: Chambers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ChamberId,Name,FromDay,ToDay,StartTime,EndTime,Phone,Email,City,Area,Address1,Address2,ZipCode,DoctorId")] Chamber chamber)
        {
            if (ModelState.IsValid)
            {
                var entry = _repository.Entry(chamber);
                entry.State = EntityState.Modified;
                entry.Property(e => e.DoctorId).IsModified = false;
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.DoctorId = new SelectList(_repository.Doctors, "DoctorId", "Firstname", chamber.DoctorId);
            return View(chamber);
        }

        // GET: Chambers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamber chamber = await _repository.Chambers.FindAsync(id);
            if (chamber == null)
            {
                return HttpNotFound();
            }
            return View(chamber);
        }

        // POST: Chambers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Chamber chamber = await _repository.Chambers.FindAsync(id);
            _repository.Chambers.Remove(chamber);
            await _repository.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientHelpCare/Controllers/LayoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientHelpCare.Controllers
{
    public class LayoutsController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OffCanvas()
        {
            return View();
        }
	}
}

PatientHelpCare/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientHelpCare.DataModel;

namespace PatientHelpCare.Controllers
{
    public class MessagesController : Controller
    {
        private Doctor_InformationEntities _repository = new Doctor_InformationEntities();

        // GET: Messages
        public async Task<ActionResult> Index()
        {
            var User = _repository.AspNetUsers.Where(x => x.Email == HttpContext.User.Identity.Name).FirstOrDefault();
            ViewBag.UserType = User.UserType;
            if(User.UserType == "Doctor")
            {
                var messages = _repository.Messages.Include(m => m.Patient);
                return View(await messages.Where(x => x.DoctorId == User.Id).ToListAsync());
            }
            else
            {
                var messages = _repository.Messages.Include(m => m.Doctor);
                return View(await messages.Where(x => x.PatientId == User.Id).ToListAsync());
            }
            return View();
        }

        public ActionResult EmailView()
        {
            var CurrentUser = _repository.AspNetUsers.Where(x => x.Email == HttpContext.User.Identity.Name).FirstOrDefault();
            if (CurrentUser.UserType == "Doctor")
            {
                var LastMessage = _repository.Messages.Where(x => x.DoctorId == CurrentUser.Id).OrderByDescending(x => x.DateTime).FirstOrDefault();
                ViewBag.LastMessage = LastMessage;
                var Sentby = _repository.AspNetUsers.Where(x => x.Id == LastMessage.Sentby).FirstOrDefault();
                ViewBag.From = Sentby;
            }
            else
            {
                var LastMessage = _repository.Messages.Where(x => x.PatientId == CurrentUser.Id).OrderByDescending(x => x.DateTime).FirstOrDefault();
                ViewBag.LastMessage = LastMessage;
                var Sentby = _repository.AspNetUsers.Where(x => x.Id == LastMessage.Sentby).FirstOrDefault();
                ViewBag.From = Sentby;
            }
            return View();
        }

        // GET: Messages/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var CurrentUser = _repository.AspNetUsers.Where(x => x.Email == HttpContext.User.Identity.Name).FirstOrDefault();
            if (CurrentUser.UserType == "Doctor")
            {
                var LastMessage = _repository.Messages.Where(x => x.Id==id && x.DoctorId == CurrentUser.Id).OrderByDescending(x => x.DateTime).FirstOrDefault();
                ViewBag.LastMessage = LastMessage;
                var Sentby = _repository.AspNetUsers.Where(x => x.Id == LastMessage.Sentby).FirstOrDefault().Email;
                ViewBag.From = Sentby;
            }
            else
            {
                var LastMessage = _repository.Messages.Where(x => x.Id == id && x.PatientId == CurrentUser.Id).OrderByDescending(x => x.DateTime).FirstOrDefault();
                ViewBag.LastMessage = LastMessage;
                var Sentby = _repository.AspNetUsers.Where(x => x.Id == LastMessage.Sentby).FirstOrDefault().Email;
                ViewBag.From = Sentby;
            }

            Message message = await _repository.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        public ActionResult Create()
        {
            ViewBag.PatientId = new SelectList(_repository.Patients, "Id", "Firstname");
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> Create(string Email, string Subject, string Message1)
        {
            Message message = new Message();
            if (ModelState.IsValid)
            {               
                var User = _repository.AspNetUsers.Where(x => x.Email == HttpContext.User.Identity.Name).FirstOrDefault();
                if(User.UserType == "Doctor")
                {
                    message.DoctorId = User.Id;
                    message.Sentby = User.Id;

                    var Patient = _repository.AspNetUsers.Where(x => x.Email == Email).FirstOrDefault();
                    message.PatientId = Patient.Id;
                }
                else
                {
                    message.PatientId = User.Id;
                    message.Sentby = User.Id;

                    var Doctor = _repository.AspNetUsers.Where(x => x.Email == Email).FirstOrDefault();
                    message.DoctorId = Doctor.Id;
                }
                message.Message1 = Message1;
                message.Subject = Subject;
                message.MarkRead = false;
                message.DateTime = DateTime.Now;
                _repository.Messages.Add(message);
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }            
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await _repository.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientId = new SelectList(_repository.Patients, "Id", "Firstname", message.PatientId);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Subject,Message1,DoctorId,PatientId,DateTime,MarkRead,Sentby")] Message message)
        {
            if (ModelState.IsValid)
            {
                _repository.Entry(message).State = EntityState.Modified;
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PatientId = new SelectList(_repository.Patients, "Id", "Firstname", message.PatientId);
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await _repository.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Message message = await _repository.Messages.FindAsync(id);
            _repository.Messages.Remove(message);
            await _repository.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientHelpCare/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        www.ithelpcare.com
    </div>
    <div>
        <strong>Copyright</strong> Doctor Information &copy; 2016
    </div>
</div>

PatientHelpCare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Doctors information | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    
</head>
<body>

    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PatientHelpCare/Views/Shared/_Navigation.cshtml
@using PatientHelpCare.DataModel;
@{ 
    Doctor_InformationEntities db = new Doctor_InformationEntities();
    var UserId = db.AspNetUsers.Where(x => x.UserName == HttpContext.Current.User.Identity.Name).FirstOrDefault();
    Doctor lcl_doctor = new Doctor();
    if (UserId.UserType == "Doctor")
    {
        lcl_doctor = db.Doctors.Where(x => x.DoctorId == UserId.Id).FirstOrDefault();
    }
}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                @if (UserId.UserType == "Doctor")
                {
                    <div class="dropdown profile-element">
                        <span>
                            @if (lcl_doctor.PhotoLocation != null)
                            {
                                <img alt="image" class="img-circle" <img style="width:100px;height:100px;" src="@Html.DisplayFor(modelItem => lcl_doctor.PhotoLocation)" alt="" />
                            }
                            else
                            {
                                <img alt="image" class="img-circle" <img style="width:100px;height:100px;" src="~/Images/unknown.png" alt="" />
                            }
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear">
                                <span class="block m-t-xs">
                                    <strong class="font-bold">@lcl_doctor.Firstname @lcl_doctor.Lastname</strong>
                                </span> <span class="text-muted text-xs block">@lcl_doctor.Title <b class="caret"></b></span>
                            </span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="/Doctors/Details/@UserId.Id">Profile</a></li>
                            <li><a href="@Url.Action("index", "Messages")">Message</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("index", "Home")">Logout</a></li>
                        </ul>
                    </div>
                }
                
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="@Html.IsSelected(controller: "Dashboards")">
                <a href="@Url.Action("Dashboard", "Dashboards")"><i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Dashboard</span></a>                
            </li>
            
            <li class="@Html.IsSelected(controller: "Mailbox")">
                <a href="#"><i class="fa fa-envelope"></i> <span class="nav-label" data-i18n="nav.mailbox">Message </span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Messages", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Inbox")"><a href="@Url.Action("index", "Messages")">Inbox</a></li>
                    
                    <li class="@Html.IsSelected(action: "Create")"><a href="@Url.Action("Create", "Messages")">Write Message</a></li>
                    
                </ul>
            </li>
            @if (UserId.UserType == "Doctor")
            {
                    <li class="@Html.IsSelected(controller: "Doctors")">
                        <a href="#"><i class="fa fa-edit"></i> <span class="nav-label" data-i18n="nav.forms">Profile</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Doctors", cssClass: "in")">
                            <li class="@Html.IsSelected(action: "Edit Profile")"><a href="@Url.Action("Index", "Doctors")">Doctors</a></li>
                            <li class="@Html.IsSelected(action: "Add Chamber")"><a href="@Url.Action("Index", "Chambers")">Chamber</a></li>
                            <li class="@Html.IsSelected(action: "Add Experience")"><a href="@Url.Action("Index", "Experiences")">Experience</a></li>
                            <li class="@Html.IsSelected(action: "Add Qualification")"><a href="@Url.Action("Index", "Qualifications")">Qualificatiton</a></li>
                            <li class="@Html.IsSelected(action: "Add Certificate")"><a href="@Url.Action("Index", "Certificates")">Certificate</a></li>
                        </ul>
                    </li>
            }
            else
            {
                <li class="@Html.IsSelected(controller: "Profile")">
                    <a href="@Url.Action("Index", "Patients")"><i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Profile</span></a>
                </li>
               
            }
                
            @if (UserId.UserType != "Doctor")
            {
            <li class="@Html.IsSelected(controller: "Doctors")">
                <a href="@Url.Action("Doctors", "Doctors")"><i class="fa fa-files-o"></i> <span class="nav-label" data-i18n="nav.dashboard">Find Doctors</span></a>
            </li>
            }
            <li class="@Html.IsSelected(controller: "Appointment")">
                <a href="@Url.Action("Index", "Appointments")"><i class="fa fa-files-o"></i> <span class="nav-label" data-i18n="nav.dashboard">Appointment</span></a>
            </li>            
        </ul>
    </div>
</nav>

PatientHelpCare/Views/Shared/_SkinConfig.cshtml
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-setttings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                <span>
                    Collapse menu
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed sidebar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar v.2
                    <br />
                    <small>*Primary layout</small>
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Boxed layout
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed footer
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-0">
                        Default
                    </a>
                </span>
            </div>
            <div class="setings-item blue-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-1">
                        Blue light
                    </a>
                </span>
            </div>
            <div class="setings-item yellow-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-3">
                        Yellow/Purple
                    </a>
                </span>
            </div>
            <div class="setings-item ultra-skin">
                <span class="skin-name ">
                    <a target="_blank" href="md_skin/" class="md-skin">
                        Material Design
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

PatientHelpCare/Views/Shared/_TopNavbar2.cshtml
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
            </button>
            <a href="#" class="navbar-brand">Doctors information</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a aria-expanded="false" role="button" href="@Url.Action("Index", "Layouts")"> Back to main Layout page</a>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>

            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="#">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>